name: Build and Release

on:
  push:
    branches: [main, master]
    tags:
      - "v*"
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        env:
          MOD_VERSION: ${{ github.ref_name }}
        run: |
          if [[ "$MOD_VERSION" == v* ]]; then
            ./gradlew build -Pmod_version=${MOD_VERSION#v}
          else
            ./gradlew build
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SwingFarm-Build
          path: build/libs/*.jar

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          TAG_NAME="${{ github.ref_name }}"
          MOD_VERSION="${TAG_NAME#v}"

          NOTES_TEMPLATE=".github/release.md"
          RELEASE_NOTES="release-notes.md"

          cp "$NOTES_TEMPLATE" "$RELEASE_NOTES"
          sed -i "s/%%VERSION%%/$TAG_NAME/g" "$RELEASE_NOTES"
          sed -i "s/%%MOD_VERSION%%/$MOD_VERSION/g" "$RELEASE_NOTES"

          gh release create "$TAG_NAME" \
            --title "$TAG_NAME" \
            --notes-file "$RELEASE_NOTES" \
            --prerelease \
            "build/libs/swingfarm-fabric-1.21.5-$MOD_VERSION.jar"
